# Generated by Django 3.2.9 on 2021-12-06 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comment',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='author',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment_date',
        ),
    ]
